### ISSUE TITLE
Open selected file(s) in (v)new buffer instead of a new tab.

### ISSUE THREAD

**Issue by phrohdoh** [Mizuchi/vim-ranger#7]
Would this at all be possible?
My workflow _rarely_ consist of tabs, but I use splits often.

**Comment by Mizuchi** [comment]
if you want to open file in buffer, you might want to use the following plugin instead:
https://github.com/hut/ranger/blob/master/examples/vim_file_chooser.vim

This plugin is released as a part of ranger. If you use archlinux you could just create a link in your vim configuration.

  ln /usr/share/doc/ranger/examples/vim_file_chooser.vim ~/.vim/plugin

My plugin is forked from this file and the reason I fork it is because
1. I prefer tabs rather than buffers
2. my plugin will open ranger automatically when you :edit a directory

If you don't care (2), then the original plugin is a better choice for you. 

Though it's not hard to implement but I prefer to keep my plugin simple. I might considering contribute this back to ranger project if there are many people who cares (2).

**Comment by phrohdoh** [comment]
Okay, thanks!
